import React, { useRef, useEffect, useState } from 'react';
import Head from "next/head";
import mapboxgl, { type Map } from 'mapbox-gl';

mapboxgl.accessToken = 'pk.eyJ1IjoiZGFpc2hvYXJjaCIsImEiOiJjbG13OW5keWMwOTRtMmtsMnN1YmtobmdtIn0.X1iVg56KI3O6tbUYFJmd5Q'

export default function Home() {
	const mapContainer = useRef<HTMLDivElement>(null);
	const map = useRef<Map | null>(null);
	const [lng, setLng] = useState(-95.0992011);
	const [lat, setLat] = useState(29.5555885);

	useEffect(() => {
		if (map.current ?? !mapContainer.current) return; // initialize map only once
		map.current = new mapboxgl.Map({
			container: mapContainer.current,
			projection: {
				name: 'globe'
			},
			style: 'mapbox://styles/mapbox/streets-v12',
			center: [lng, lat],
			zoom: window.innerWidth < 640 ? 0.5 : 3
		});
	}, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<div ref={mapContainer} className="map-container w-full h-screen"></div>

			<div className='flex flex-col gap-4 absolute bottom-4 right-4'>
				<button className='btn circle flex-center' onClick={() => map.current?.zoomIn()}>
					<svg viewBox="0 0 24 24" fill="none" className='w-6 h-6' xmlns="http://www.w3.org/2000/svg">
						<path d="M4 12H20M12 4V20" stroke="#fff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
					</svg>
				</button>
				<button className='btn circle flex-center' onClick={() => map.current?.zoomOut()}>
					<svg viewBox="0 0 24 24" fill="none" className='w-6 h-6' xmlns="http://www.w3.org/2000/svg">
						<path d="M6 12L18 12" stroke="#fff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
					</svg>
				</button>
			</div>
    </>
  );
}
